#!/usr/bin/env python3
"""Structural lint for JSON-UI screen files (#208).

panelkit.py closes trap 1 and trap 2 at *generation* time -- a screen built
with its primitives can't emit the bad shapes at all. This module re-checks
the same rules *structurally*, by walking a screen.json tree, so it also
catches a screen that was hand-written or generated by something else (the
counter-example this lint is calibrated against is
apps/tunastreet.xviewer/res/screens/home.json, which predates panelkit).

panelkit.py imports this module and calls lint_tree() on every screen it
builds (see the bottom of this file), so a screen assembled purely from
panelkit primitives is linted the moment it's built, not just at flash time.

Run standalone: `python3 lint.py <screen.json> [...]`
"""
import json
import sys

import tokens as tk

FLEX_LAYOUT_TYPES = ("flex", "grid")
# Event types that represent an actual tap/touch target, as opposed to e.g. a
# screen-level "gesture" (swipe) listener -- pressLock/scrollable are a tap
# target's contract, not a gesture listener's, so R2's structural checks only
# apply when one of these is present.
TAP_EVENT_TYPES = ("pressed", "released", "pressing", "clicked")


def _walk(node, path, out):
    """Yield (node, path) for node and every descendant, depth-first."""
    out.append((node, path))
    for i, c in enumerate(node.get("children", []) or []):
        cid = c.get("id", str(i))
        _walk(c, path + "/" + cid, out)


def _box(node):
    """Absolute box (x, y, w, h) for a node, or None if it isn't absolute."""
    p = node.get("placement", {})
    if p.get("mode") == "absolute" or ("x" in p and "y" in p):
        x, y = p.get("x", 0), p.get("y", 0)
        w, h = p.get("width", 0), p.get("height", 0)
        return x, y, w, h
    return None


def lint_tree(root, file_label="screen"):
    """Return a list of "file:/node/path rule message" violation strings."""
    nodes = []
    _walk(root, "", nodes)
    violations = []

    def report(node, path, rule, msg):
        nid = node.get("id", "?")
        violations.append("%s:%s/%s %s %s" % (file_label, path, nid, rule, msg))

    # R1 -- trap 1: a flex/grid container with an absolute-placed child.
    for node, path in nodes:
        layout_type = node.get("layout", {}).get("type")
        if layout_type in FLEX_LAYOUT_TYPES:
            for c in node.get("children", []) or []:
                p = c.get("placement", {})
                if p.get("mode") == "absolute" or ("x" in p and "y" in p and "mode" not in p):
                    report(node, path, "R1",
                           "container has layout.type=%r but child %r is "
                           "absolute-placed (trap 1: the parent's flex layout "
                           "silently overrides it)" % (layout_type, c.get("id")))

    # R2 -- trap 2: requireValidPress anywhere; a tap target (has `events`)
    # missing pressLock:true or with scrollable not false.
    for node, path in nodes:
        for ev in node.get("events", []) or []:
            for eff in ev.get("effects", []) or []:
                if eff.get("requireValidPress"):
                    report(node, path, "R2",
                           "requireValidPress:true drops a tap the finger "
                           "drifted through (trap 2)")
        is_tap_target = any(ev.get("type") in TAP_EVENT_TYPES for ev in node.get("events", []) or [])
        if is_tap_target:
            cp = node.get("commonProps", {})
            if cp.get("pressLock") is not True:
                report(node, path, "R2",
                       "has events but commonProps.pressLock is not true "
                       "(trap 2: a drifted press can be lost)")
            if cp.get("scrollable", False) is not False:
                report(node, path, "R2",
                       "has events but commonProps.scrollable is not false "
                       "(trap 2: a small drag becomes a scroll, not a press)")

    # R3 -- text floor: any label under tokens.text.floor.
    for node, path in nodes:
        if node.get("type") == "label":
            size = node.get("style", {}).get("fontSize")
            if size is not None and size < tk.TEXT_FLOOR:
                report(node, path, "R3",
                       "fontSize %d is below the text floor (%d)" % (size, tk.TEXT_FLOOR))

    # R4 -- target spacing: sibling tap targets closer than target_gap_min.
    # Gated to boxes at or under target_h_max: the #205 "blob" failure was
    # control-sized chrome (buttons near the touch-target band) packed a few
    # px apart. A big content tile (a car-select card, well over the band) is
    # already visually and spatially distinct at any gap, and a set of
    # full-bleed adjacent zones tiling a region with *zero* gap (racing's
    # lane thirds -- "target the outcome, not the control", tokens.json
    # touch.note) is the deliberate fix for this trap, not another instance
    # of it: there's no ambiguous sliver between them for a tap to land in.
    for node, path in nodes:
        targets = [c for c in (node.get("children", []) or []) if c.get("events")]
        boxes = [(c, _box(c)) for c in targets]
        boxes = [(c, b) for c, b in boxes if b is not None and b[3] <= tk.TARGET_H_MAX]
        for i in range(len(boxes)):
            for j in range(i + 1, len(boxes)):
                c1, (x1, y1, w1, h1) = boxes[i]
                c2, (x2, y2, w2, h2) = boxes[j]
                gap = _gap_between((x1, y1, w1, h1), (x2, y2, w2, h2))
                if gap is not None and gap < tk.TARGET_GAP_MIN:
                    report(node, path, "R4",
                           "tap targets %r and %r are %dpx apart, below "
                           "target_gap_min (%d)" % (c1.get("id"), c2.get("id"),
                                                     gap, tk.TARGET_GAP_MIN))

    # R5 -- off-panel: any absolute node whose box escapes the device bounds.
    # A node whose placement.x/y is runtime-bound (racing's obstacles staged
    # at y=-90 above the visible road before app.js animates them in) has a
    # static JSON position that's an initial value, not a rendered one --
    # off-panel is only meaningful for a position the JSON itself controls.
    for node, path in nodes:
        b = _box(node)
        if b is None:
            continue
        bound_axes = set(k.split(".", 1)[1] for k in node.get("bindings", {})
                          if k.startswith("placement."))
        if "x" in bound_axes or "y" in bound_axes:
            continue
        x, y, w, h = b
        if x < 0 or y < 0 or x + w > tk.W or y + h > tk.H:
            report(node, path, "R5",
                   "box (%d,%d,%d,%d) escapes the %dx%d panel"
                   % (x, y, w, h, tk.W, tk.H))

    return violations


def _gap_between(b1, b2):
    """Shortest axis-aligned gap between two boxes; overlapping -> 0."""
    x1, y1, w1, h1 = b1
    x2, y2, w2, h2 = b2
    dx = max(x1, x2) - min(x1 + w1, x2 + w2)
    dy = max(y1, y2) - min(y1 + h1, y2 + h2)
    if dx <= 0 and dy <= 0:
        return 0  # overlapping in both axes
    return max(dx, 0, dy)


def lint_file(path):
    with open(path) as f:
        root = json.load(f)
    return lint_tree(root, file_label=path)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage: python3 lint.py <screen.json> [...]", file=sys.stderr)
        sys.exit(2)
    all_violations = []
    for path in sys.argv[1:]:
        all_violations.extend(lint_file(path))
    for v in all_violations:
        print(v)
    sys.exit(1 if all_violations else 0)
