#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Steven Matison
#
# SPDX-License-Identifier: Apache-2.0
"""Structural lint for JSON-UI screen files.

panelkit.py closes trap 1 and trap 2 at *generation* time -- a screen built
with its primitives can't emit the bad shapes at all. This module re-checks
the same rules *structurally*, by walking a screen.json tree, so it also
catches a screen that was hand-written or generated by something else (the
counter-example this lint is calibrated against is
apps/tunastreet.xviewer/res/screens/home.json, which predates panelkit).

panelkit.py imports this module and calls lint_tree() on every screen it
builds (see the bottom of this file), so a screen assembled purely from
panelkit primitives is linted the moment it's built, not just at flash time.

Rules R1-R10, the same set and the same numbers as the pre-flash check
(tools/simulator/lint.js), both reading their thresholds from
tokens.json. lint.js additionally has R0, a *dynamic* reachability check
that needs a booted app -- that one has no structural twin here.

Run standalone: `python3 lint.py <screen.json> [...]`
"""
import json
import sys

import tokens as tk

# The rule inventory, in one place so the linter can describe itself
# (`python3 lint.py --rules`) and so selftest.py can assert that the pre-flash
# twin (tools/simulator/lint.js) implements the same set. Two linters that
# quietly drift apart are worse than one: a generator would pass its own gate
# and fail at flash time, or -- the dangerous direction -- pass both and fail
# on the glass. lint.js additionally has R0, a *dynamic* reachability check
# that needs a booted app and has no structural twin here.
RULES = {
    "R1": "trap 1 -- a flex/grid container with an absolute-placed child",
    "R2": "trap 2 -- requireValidPress, or a tap target without pressLock/scrollable:false",
    "R3": "text below the readable floor",
    "R4": "two sibling tap targets closer than the minimum gap",
    "R5": "an absolute node whose box escapes the panel",
    "R6": "trap 3 -- an image that does not declare clickable, so it swallows taps",
    "R7": "trap 4 -- text outside ASCII, which the built-in Montserrat cannot draw",
    "R8": "a fontSize that is not on the compiled Montserrat ladder",
    "R9": "a label box shorter than the font's real line height",
    "R10": "edge-anchored text sitting inside the glass's rounded corner",
}

FLEX_LAYOUT_TYPES = ("flex", "grid")
# Event types that represent an actual tap/touch target, as opposed to e.g. a
# screen-level "gesture" (swipe) listener -- pressLock/scrollable are a tap
# target's contract, not a gesture listener's, so R2's structural checks only
# apply when one of these is present.
TAP_EVENT_TYPES = ("pressed", "released", "pressing", "clicked")


def _walk(node, path, out):
    """Yield (node, path) for node and every descendant, depth-first."""
    out.append((node, path))
    for i, c in enumerate(node.get("children", []) or []):
        cid = c.get("id", str(i))
        _walk(c, path + "/" + cid, out)


def _box(node):
    """Absolute box (x, y, w, h) for a node, or None if it isn't absolute."""
    p = node.get("placement", {})
    if p.get("mode") == "absolute" or ("x" in p and "y" in p):
        x, y = p.get("x", 0), p.get("y", 0)
        w, h = p.get("width", 0), p.get("height", 0)
        return x, y, w, h
    return None


def _geometry(root):
    """Map id(node) -> (abs_x, abs_y, w, h) for every node whose position is
    knowable from the JSON alone.

    A node qualifies when it and every ancestor up to the root are
    absolute-placed: then its screen position is just the running sum of the
    x/y chain. A flow-placed node's position is decided by its parent's flex
    layout at runtime, so it is left out of the map entirely and the geometry
    rules (R5, R10) skip it -- tools/simulator/lint.js has a layout pass that
    can estimate those, this one deliberately does not guess.
    """
    geo = {}

    def visit(node, ox, oy, placed):
        b = _box(node)
        if placed and b is not None:
            x, y, w, h = b
            ax, ay = ox + x, oy + y
            geo[id(node)] = (ax, ay, w, h)
            cox, coy, cplaced = ax, ay, True
        else:
            # Root viewScreen has no placement of its own but IS the origin.
            if placed and b is None and not node.get("placement"):
                cox, coy, cplaced = ox, oy, True
            else:
                cox, coy, cplaced = 0, 0, False
        for c in node.get("children", []) or []:
            visit(c, cox, coy, cplaced)

    visit(root, 0, 0, True)
    return geo


def lint_tree(root, file_label="screen"):
    """Return a list of "file:/node/path rule message" violation strings."""
    nodes = []
    _walk(root, "", nodes)
    geo = _geometry(root)
    violations = []

    def report(node, path, rule, msg):
        nid = node.get("id", "?")
        violations.append("%s:%s/%s %s %s" % (file_label, path, nid, rule, msg))

    # R1 -- trap 1: a flex/grid container with an absolute-placed child.
    for node, path in nodes:
        layout_type = node.get("layout", {}).get("type")
        if layout_type in FLEX_LAYOUT_TYPES:
            for c in node.get("children", []) or []:
                p = c.get("placement", {})
                if p.get("mode") == "absolute" or ("x" in p and "y" in p and "mode" not in p):
                    report(node, path, "R1",
                           "container has layout.type=%r but child %r is "
                           "absolute-placed (trap 1: the parent's flex layout "
                           "silently overrides it)" % (layout_type, c.get("id")))

    # R2 -- trap 2: requireValidPress anywhere; a tap target (has `events`)
    # missing pressLock:true or with scrollable not false.
    for node, path in nodes:
        for ev in node.get("events", []) or []:
            for eff in ev.get("effects", []) or []:
                if eff.get("requireValidPress"):
                    report(node, path, "R2",
                           "requireValidPress:true drops a tap the finger "
                           "drifted through (trap 2)")
        is_tap_target = any(ev.get("type") in TAP_EVENT_TYPES for ev in node.get("events", []) or [])
        if is_tap_target:
            cp = node.get("commonProps", {})
            if cp.get("pressLock") is not True:
                report(node, path, "R2",
                       "has events but commonProps.pressLock is not true "
                       "(trap 2: a drifted press can be lost)")
            if cp.get("scrollable", False) is not False:
                report(node, path, "R2",
                       "has events but commonProps.scrollable is not false "
                       "(trap 2: a small drag becomes a scroll, not a press)")

    # R3 -- text floor: any label under tokens.text.floor.
    for node, path in nodes:
        if node.get("type") == "label":
            size = node.get("style", {}).get("fontSize")
            if size is not None and size < tk.TEXT_FLOOR:
                report(node, path, "R3",
                       "fontSize %d is below the text floor (%d)" % (size, tk.TEXT_FLOOR))

    # R4 -- target spacing: sibling tap targets closer than target_gap_min.
    # Gated to boxes at or under target_h_max. The ambiguity this guards
    # against is between two discrete, similarly-sized controls. A content
    # tile well above the band is already distinct at any gap, and adjacent
    # zones tiling a region with zero gap leave no sliver for a tap to fall
    # into -- neither is an instance of the failure.
    for node, path in nodes:
        targets = [c for c in (node.get("children", []) or []) if c.get("events")]
        boxes = [(c, _box(c)) for c in targets]
        boxes = [(c, b) for c, b in boxes if b is not None and b[3] <= tk.TARGET_H_MAX]
        for i in range(len(boxes)):
            for j in range(i + 1, len(boxes)):
                c1, (x1, y1, w1, h1) = boxes[i]
                c2, (x2, y2, w2, h2) = boxes[j]
                gap = _gap_between((x1, y1, w1, h1), (x2, y2, w2, h2))
                if gap is not None and gap < tk.TARGET_GAP_MIN:
                    report(node, path, "R4",
                           "tap targets %r and %r are %dpx apart, below "
                           "target_gap_min (%d)" % (c1.get("id"), c2.get("id"),
                                                     gap, tk.TARGET_GAP_MIN))

    # R5 -- off-panel: any absolute node whose box escapes the device bounds.
    # A node whose placement.x/y is runtime-bound (racing's obstacles staged
    # at y=-90 above the visible road before app.js animates them in) has a
    # static JSON position that's an initial value, not a rendered one --
    # off-panel is only meaningful for a position the JSON itself controls.
    for node, path in nodes:
        b = _box(node)
        if b is None:
            continue
        bound_axes = set(k.split(".", 1)[1] for k in node.get("bindings", {})
                          if k.startswith("placement."))
        if "x" in bound_axes or "y" in bound_axes:
            continue
        abs_box = geo.get(id(node))
        if abs_box is None:
            continue  # flow-placed: position is the parent's flex to decide
        x, y, w, h = abs_box
        if x < 0 or y < 0 or x + w > tk.W or y + h > tk.H:
            report(node, path, "R5",
                   "box (%d,%d,%d,%d) escapes the %dx%d panel"
                   % (x, y, w, h, tk.W, tk.H))

    # R6 -- trap 3: an image with no explicit `clickable`. The runtime
    # defaults an image node to clickable:true, so a decorative picture drawn
    # over a tap zone eats every tap that lands on it and the zone below never
    # sees one.
    for node, path in nodes:
        if node.get("type") != "image":
            continue
        if "clickable" not in (node.get("commonProps") or {}):
            report(node, path, "R6",
                   "image does not declare commonProps.clickable -- the "
                   "runtime defaults it to true and it will swallow taps "
                   "meant for whatever is underneath")

    # R7 -- trap 4: text the panel font cannot draw. No FreeType on this
    # board means built-in Montserrat, which is ASCII only; anything else is
    # a white box on the glass.
    for node, path in nodes:
        text = (node.get("labelProps") or {}).get("text")
        if not isinstance(text, str):
            continue
        for ch in text:
            if ord(ch) > 126 or (ord(ch) < 32 and ch != "\n"):
                report(node, path, "R7",
                       "text %r contains U+%04X, outside the built-in "
                       "Montserrat's ASCII range -- renders as a white box"
                       % (text, ord(ch)))
                break

    # R8 -- the compiled font ladder. There is no FreeType and no TinyTTF in
    # this build, so a fontSize is not scaled to order: get_builtin_font()
    # (gui/brookesia_gui_lvgl/src/style_font.cpp) returns an exact match or
    # else the closest SMALLER compiled Montserrat face. An off-ladder size
    # therefore renders silently smaller than it reads in the source -- the
    # shell's 11sp clock was drawn at 8px, and a 56px "hero" is really 48px.
    for node, path in nodes:
        size = (node.get("style") or {}).get("fontSize")
        if not isinstance(size, int) or size in tk.FONT_LADDER:
            continue
        drawn = max([r for r in tk.FONT_LADDER if r < size], default=None)
        report(node, path, "R8",
               "fontSize %d is not a compiled Montserrat size -- it will "
               "render at %s. Use one of: %s"
               % (size,
                  ("%dpx" % drawn) if drawn is not None else
                  "the LVGL default (no smaller face exists)",
                  ", ".join(str(r) for r in tk.FONT_LADDER)))

    # R9 -- a label box shorter than the font's real line height clips
    # descenders. The heights are the actual .line_height out of each
    # lv_font_montserrat_<n>.c, not the desktop habit of ~1.3x the nominal
    # size: the real ratio is ~1.1x, and guessing high falsely condemns boxes
    # that are fine while hiding the ones that are not.
    for node, path in nodes:
        if node.get("type") != "label":
            continue
        size = (node.get("style") or {}).get("fontSize")
        h = (node.get("placement") or {}).get("height")
        need = tk.LINE_HEIGHT.get(size)
        if need is not None and isinstance(h, int) and h < need:
            report(node, path, "R9",
                   "label box is %dpx tall but Montserrat %d has a line "
                   "height of %dpx -- descenders will be clipped"
                   % (h, size, need))

    # R10 -- edge-anchored text sitting inside a rounded corner. The glass is
    # a rounded rectangle, so near the top and bottom edges the usable width
    # is narrower than the panel: text at the normal 16px edge inset but only
    # a few px down is inside the arc and reads as jammed into the curve.
    # Only left/right-aligned text is at risk -- a centred label's box can
    # span the full width while its glyphs sit safely in the middle.
    for node, path in nodes:
        if node.get("type") != "label" or not tk.CORNER_RADIUS:
            continue
        abs_box = geo.get(id(node))
        if abs_box is None:
            continue
        align = (node.get("style") or {}).get("textAlign", "left")
        if align == "center":
            continue
        x, y, w, h = abs_box
        d = min(max(y, 0), max(tk.H - (y + h), 0))
        need = tk.corner_inset(d)
        if need <= 0:
            continue
        if align == "left" and x < need:
            report(node, path, "R10",
                   "left-aligned text starts at x=%d but the rounded corner "
                   "needs x>=%d this close to the edge (%dpx). Move it down "
                   "or in." % (x, need, d))
        elif align == "right" and (tk.W - (x + w)) < need:
            report(node, path, "R10",
                   "right-aligned text ends at x=%d but the rounded corner "
                   "needs it to end by x<=%d this close to the edge (%dpx). "
                   "Move it down or in." % (x + w, tk.W - need, d))

    return violations


def _gap_between(b1, b2):
    """Shortest axis-aligned gap between two boxes; overlapping -> 0."""
    x1, y1, w1, h1 = b1
    x2, y2, w2, h2 = b2
    dx = max(x1, x2) - min(x1 + w1, x2 + w2)
    dy = max(y1, y2) - min(y1 + h1, y2 + h2)
    if dx <= 0 and dy <= 0:
        return 0  # overlapping in both axes
    return max(dx, 0, dy)


def lint_file(path):
    with open(path) as f:
        root = json.load(f)
    return lint_tree(root, file_label=path)


if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == "--rules":
        for rid in sorted(RULES, key=lambda r: int(r[1:])):
            print("%-4s %s" % (rid, RULES[rid]))
        sys.exit(0)
    if len(sys.argv) < 2:
        print("usage: python3 lint.py <screen.json> [...]\n"
              "       python3 lint.py --rules", file=sys.stderr)
        sys.exit(2)
    all_violations = []
    for path in sys.argv[1:]:
        all_violations.extend(lint_file(path))
    for v in all_violations:
        print(v)
    sys.exit(1 if all_violations else 0)
